# Generated by Django 3.0.5 on 2023-05-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20230510_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coding_view',
        ),
        migrations.AlterField(
            model_name='coding_result',
            name='coding_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.coding_course'),
        ),
    ]
