# Generated by Django 3.0.5 on 2023-05-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
